#!/bin/bash

SBATCH --job-name=bossdb-mesh
SBATCH --ntasks-per-node=8
SBATCH --mem=64G
SBATCH --time=00:15:00

# Copyright (c) 2025 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Daniel Xenes

# make output directory
OUTPUT_DIR="out"
mkdir -p $OUTPUT_DIR

# run the actual python code
singularity exec docker://brainlife/bossdb-mesh python3 mesh.py